### ISSUE TITLE
Spec compilation fail after version 3.2.5

### ISSUE THREAD

**Issue by dbackeus** [jfirebaugh/konacha#188]
When upgrading konacha from 3.2.4 to 3.2.5 (and 3.3.0) we get compilation errors such as:

```
Failed:  models/story_module_spec.js.coffee
Error: Failed to load models/story_module_spec.js.coffee.
Perhaps it failed to compile? Check the rake output for errors.
```

This seem to happen rarely and randomly on our development machines but always on Semaphore (used for CI, where assets are pre compiled on every new build).
